---
- name: Deploy Flask app via Docker
  hosts: localhost
  become: yes

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Remove existing Flask container (if any)
      shell: |
        docker rm -f flask-demo || true

    - name: Run new Flask container
      shell: |
        docker run -d -p 5000:5000 --name flask-demo python:3.9-slim bash -c "pip install flask && python -m flask run --host=0.0.0.0"
